### PR TITLE
[PR] Adding max attributes to the action list and missing localization for them

### LINKED ISSUE #1137: [Bug] ActiveEffect Autocomplete doesn't return "max" for bar resources
**Describe the bug**
In ActiveEffect settings dialog, when you select bar attribute key (like hit points, stress, etc) the returned string is the resource object instead of its max value

**To Reproduce**

**Expected behavior**

**Screenshots**

**Setup Information:**
 - OS: [e.g. iOS, Windows]
 - Foundry Version [e.g. v13 b342]
- System Version [e.g. v.1.0, v.1.0.1]

**Additional context**

### PR DESCRIPTION
**Pull request by nsalyzyn**
## Description

Added an option for max values for those in the `bar` category of attributes. eg. stress, hp and hope.

- Fixes #1137 

## Type of Change

Please check the relevant options:

- [X] Bug fix
- [ ] New feature
- [ ] Code cleanup/refactor
- [ ] Documentation update
- [ ] Test coverage
- [ ] Dependency update
- [ ] Configuration change
- [ ] Other (please describe):

## How Has This Been Tested?

In the effect dialog, under changes and in the autocomplete popup:

* Looking for max hp, max stress in adversaries
* Looking for max hp, max stress, and max hope in characters
* Looking for max stress in companions

- [X] Manual testing
- [ ] Other:

## Screenshots (if applicable)

Screenshot 2025-12-18 201136

## Checklist

- [X] My code follows the project style guidelines
- [X] I have performed a self-review of my code
- [X] I have commented my code where necessary
- [ ] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings or errors
- [ ] I have added tests that prove my fix or feature works
- [X] New and existing tests pass locally with my changes

### CODE REVIEW

**Comment by Ikraik** [comment]
hmm not keen on this for me. It is good for search but not sure. I tagged Harry for review as he was assigned to it earlier and would have a better hold if this is good or not.

File: module/data/actor/adversary.mjs [hunk 1]
```diff
@@ -59,15 +59,13 @@ export default class DhpAdversary extends BaseDataActor {
                     0,
                     0,
                     'DAGGERHEART.GENERAL.HitPoints.plural',
-                    true,
-                    game.i18n.localize('DAGGERHEART.GENERAL.max')
```
Comment (WBHarry) [inline module/data/actor/adversary.mjs:64]: I think we should keep the custom label here. The reason is that we are constrained for space, and just having `current`/`max` should be fine, since the fields are in a fieldset context already, making it clear what they are referring to.
Removing it leads to a title that won't fit in any good way.
image
Compared to
image

File: module/data/actor/adversary.mjs [hunk 2]
```diff
@@ -59,15 +59,13 @@ export default class DhpAdversary extends BaseDataActor {
...
+                    true
                 ),
                 stress: resourceField(
                     0,
                     0,
                     'DAGGERHEART.GENERAL.stress',
-                    true,
-                    game.i18n.localize('DAGGERHEART.GENERAL.max')
```
Comment (WBHarry) [inline module/data/actor/adversary.mjs:71]: Same as above.

**Comment by nsalyzyn** [comment]
I see. That would leave two entries in the autocomplete that read as "Max" in the adversary section... I'm not sure that will be easy to workaround, since the translations in the autocomplete seem pretty automated. I might have to find locations where max needs to be shortened elsewhere - like the example you've shown.

**Comment by WBHarry** [comment]
Ah, right. Well, another way around it is to do the change you did, and then just overwrite the label in the templates

**Review by WBHarry — APPROVED** [review]
🤖 :+1:
