### PR TITLE
[Fix] Enricher fixes for [[fr]] and reaction argument lazy fix 

### LINKED ISSUE #1584: [Bug] `[[/fr type=fear]]` or [[/fr type=hope]] don't work
If you use `[[/fr type=fear]]` or [[/fr type=hope]] inside a macro or a journal it will not work an generate an error. `[[/fr]]` works well.

v1.6.0

Image

Image

### PR DESCRIPTION
**Pull request by Ikraik**
## Description

Fixed issue where [[/fr]] would not create the button and failed to catch with the arguments and updated d20 dialog lazily to accept roll.type as well. 

- Fixes #1584 #1585 #1583 
- Closes  #1584 #1585 #1583 

## Type of Change

Please check the relevant options:

- [x] Bug fix (For /dr)
- [x] Code cleanup/refactor (For Regex)

## How Has This Been Tested?

Please describe the tests you ran to verify your changes:

- [x] Manual testing

## Screenshots (if applicable)

image

image

## Checklist

- [x] I have performed a self-review of my code
- [x] I have commented my code where necessary
- [x] My changes generate no new warnings or errors

## Additional Comments

<del>Need more indepth check on #1585 for /dr implementation. </del>

### CODE REVIEW

File: module/applications/dialogs/d20RollDialog.mjs [hunk 1]
```diff
@@ -9,7 +9,7 @@ export default class D20RollDialog extends HandlebarsApplicationMixin(Applicatio
         this.roll = roll;
         this.config = config;
         this.config.experiences = [];
-        this.reactionOverride = config.actionType === 'reaction';
+        this.reactionOverride = config.actionType === 'reaction'|| config.roll?.type === 'reaction';
```
Comment (Ikraik) [inline module/applications/dialogs/d20RollDialog.mjs]: I will check in to see if I need to do within the enricher itself but this is a lazy fix for now.

Comment (Ikraik) [reply module/applications/dialogs/d20RollDialog.mjs]: MAde the change
