### PR TITLE
[V14] 1354 - Armor Effect

### LINKED ISSUE #1099: [Feature]  Items/Spells that provide Armor Slots should tracked marked slots
**Description**
A character's Armor Slots are counted from (at least) the Armor, Shield and potentially Spells. Currently the character shows this as one pool. However, when one source is changed or removed, the marked slots for that source should go with the source.

So a player should be able to mark Armor slots used against specific sources. For example, if Tava's Armor has been put on the character, it's likely this will be marked first. When the Tava's Armor is consumed, the marked slot should go with it, not remain on the character. 

The same applies with a Shield. These can be removed or added during combat, so the Armor Slots can change - the amount clear and the maximum. Putting on a Shield should check that any previously marked Armor Slots are still marked.

Having separate Armor Slot "shield pools" on the character sheet can be one way to show the player where the Armor Slots are coming from, and allow them to mark specific things when necessary. The current numeric display of Armor Slots would need a rethink.

Items in the character's inventory that provide Armor Slots should be able to show marked slots while unequipped.

### LINKED ISSUE #1256: [Bug]  Equipping a shield without putting armor on doesn't give armor slots.
**Describe the bug**
DEVELOPMENT BRANCH

Equipping a shield without putting armor on doesn't give armor slots.

**To Reproduce**
1. Create a character with a shield
2. Equip the shield, but do not equip armor
3. See error - no armor slots appear

**Expected behavior**
Armor slot(s) should appear if you are using a shield but are unarmored.

**Setup Information:**
 - USE DEVELOPMENT BRANCH

### LINKED ISSUE #1354: [Feature] Armor System Improvement
**Description**
A more detailed version of the armor system to provide more customizability on where it can be marked. Also to track with automation with priority based which can be customizable. Probably noting any affected system that may utilize it like rest functions, item destruction, etc.

### PR DESCRIPTION
**Pull request by WBHarry**
Fixes #1354 
Fixes #1256 
Fixes #1099 

Potentially some styling from Molilo for the DamageReductionDialog and ArmorManagement tooltip.

### CODE REVIEW

**Comment by WBHarry** [comment]
It's some combination of bad compendium - already migrated world that you then overwrote the compendium on again when changing branch.
I just tested, and the armour slots do work 🙃

**Comment by WBHarry** [comment]
Rolls failing is known. It's an issue unrelated to armor. https://github.com/Foundryborne/daggerheart/issues/1606

**Comment by Ikraik** [comment]
Will redo the review again

**Comment by Ikraik** [comment]
hmm was unable to do repair armor test (Short rest/long rest) due to roll. I think something to check out when we have testing 1 out as you mentioned

**Comment by Ikraik** [comment]
image
Something I noticed when exploring.

**Comment by Ikraik** [comment]
image

Edit: This occured on short and long rest armor recovery

File: module/applications/dialogs/damageReductionDialog.mjs [hunk 1]
```diff
@@ -10,7 +10,8 @@ export default class DamageReductionDialog extends HandlebarsApplicationMixin(Ap
         this.reject = reject;
         this.actor = actor;
         this.damage = damage;
-        this.damageType = damageType;
+        // this.damageType = damageType;
+        this.damageType = ['physical'];
```
Comment (CarlosFdez) [inline module/applications/dialogs/damageReductionDialog.mjs]: Test stuff?

File: module/applications/dialogs/damageReductionDialog.mjs [hunk 2]
```diff
@@ -279,11 +337,19 @@ export default class DamageReductionDialog extends HandlebarsApplicationMixin(Ap
...
     static async takeDamage() {
-        const { selectedArmorMarks, selectedStressMarks, stressReductions, currentDamage } = this.getDamageInfo();
-        const armorSpent = selectedArmorMarks.length + selectedStressMarks.length;
-        const stressSpent = selectedStressMarks.length + stressReductions.reduce((acc, red) => acc + red.cost, 0);
+        const { selectedStressMarks, stressReductions, currentDamage } = this.getDamageInfo();
+        const armorChanges = this.marks.armor.reduce((acc, source) => {
+            const amount = Object.values(source.marks).filter(x => x.selected).length;
+            if (!amount) return acc;
+
+            acc.push({ uuid: source.effect.uuid, amount });
```
Comment (CarlosFdez) [inline module/applications/dialogs/damageReductionDialog.mjs]:
```suggestion
            if (amount) acc.push({ uuid: source.effect.uuid, amount });
```

File: templates/sheets/global/tabs/tab-effects.hbs [hunk 3]
```diff
@@ -18,5 +18,6 @@
         collection=effects.inactives
         canCreate=true
         hideResources=true
+        disabled=true
```
Comment (CarlosFdez) [inline templates/sheets/global/tabs/tab-effects.hbs]: Why this flag? In what way is this related to armor? If it is related to armor, why not reuse disabledEffect?

Comment (WBHarry) [reply templates/sheets/global/tabs/tab-effects.hbs]: Honestly, I've no clue why I added this. It doesn't seem to make a difference to remove it either.
So I'll do that and chalk it up to something staying from the experimental phase 🙃

File: module/applications/dialogs/damageReductionDialog.mjs (hunk 2 above)
Comment (WBHarry) [reply module/applications/dialogs/damageReductionDialog.mjs]: :+1: Silly double logic there yeah.

File: module/applications/dialogs/damageReductionDialog.mjs (hunk 1 above)
Comment (WBHarry) [reply module/applications/dialogs/damageReductionDialog.mjs]: Yup, good catch. Moved in use of the real variable :+1:

**Comment by WBHarry** [comment]
> image Something I noticed when exploring.

Fixed this one

**Comment by WBHarry** [comment]
> image
> Edit: This occured on short and long rest armor recovery

Fixed. 🔧

File: module/documents/actor.mjs [hunk 4]
```diff
@@ -1005,4 +993,20 @@ export default class DhpActor extends Actor {
 
         return allTokens;
     }
+
+    /**@inheritdoc */
+    *allApplicableEffects({ noSelfArmor, noTransferArmor } = {}) {
```
Comment (CarlosFdez) [inline module/documents/actor.mjs:1023]: Wouldn't this be a getter, like getAllApplicableEffects()?

Comment (WBHarry) [reply module/documents/actor.mjs:1023]: allApplicableEffects is a foundry method we're overwriting

Comment (CarlosFdez) [reply module/documents/actor.mjs:1023]: Weird name then, but got it!

File: module/documents/activeEffect.mjs [hunk 5]
```diff
@@ -153,6 +155,11 @@ export default class DhActiveEffect extends foundry.documents.ActiveEffect {
     /*  Methods                                     */
     /* -------------------------------------------- */
 
+    /**@inheritdoc */
```
Comment (CarlosFdez) [inline module/documents/activeEffect.mjs]: Looks like this function can be removed
