### PR TITLE
[Fix] Itemlink Redux Revengeance

### LINKED ISSUE #396: [BUG] Feature Linking to Items
The way items like Ancestry are currently keeping track of what items are linked to them is not done very well.
Going to remake it in more robust way.

### PR DESCRIPTION
**Pull request by WBHarry**
Moved the previous `subType` property that previously used to be on Feature to be stored in a data structure on `features` type fields. This should make things much more stable.

- Closes #396

### CODE REVIEW

File: module/applications/sheets/api/base-item.mjs [hunk 1]
```diff
@@ -178,26 +178,30 @@ export default class DHBaseItemSheet extends DHApplicationMixin(ItemSheetV2) {
...
         });
     }
 
     /**
      * Remove a feature from the item.
      * @type {ApplicationClickAction}
      */
-    static async #deleteFeature(_, target) {
+    static async #deleteFeature(_, element) {
+        const target = element.closest('[data-item-uuid]');
```
Comment (joaquinpereyra98) [inline module/applications/sheets/api/base-item.mjs:170]: This is already done in the getDocFromElement function, I don't know why this line was added.

File: module/applications/sheets/api/application-mixin.mjs [hunk 2]
```diff
@@ -341,7 +341,20 @@ export default function DHApplicationMixin(Base) {
                 {
                     name: 'CONTROLS.CommonEdit',
                     icon: 'fa-solid fa-pen-to-square',
-                    callback: target => getDocFromElement(target).sheet.render({ force: true })
+                    callback: async target => {
+                        const doc = getDocFromElement(target);
+                        const appId = this.element.id;
+                        doc.apps[appId] = this;
+                        const app = await doc.sheet.render({ force: true });
+                        app.addEventListener(
```
Comment (WBHarry) [inline module/applications/sheets/api/application-mixin.mjs]: Hm..should we really add the current document to the `apps` of every single editable item linked to it just because you open it?

IE: You open an Ancestry with 3 Features and 2 subclasses. With this solution, when you open Feature#1, we set the `apps` to automatically rerender the Ancestry Sheet when updates happen on Feature#1. If we worked with `onFirstRender` and `onClose`, then we'd have to register the Ancestry sheet application in the apps of all the 5 documents right away, and then remove them onClose.

Comment (joaquinpereyra98) [reply module/applications/sheets/api/application-mixin.mjs]: > If we worked with onFirstRender and onClose, then we'd have to register the Ancestry sheet application in the apps of all the 5 documents right away, and then remove them onClose.

No, You can do the same in these methods, just add a new option with the current document and check if that option exists when the application is rendered it is added.

File: templates/sheets/items/class/settings.hbs [hunk 3]
```diff
@@ -57,7 +57,7 @@
                             <img class="image" src="{{document.system.characterGuide.suggestedSecondaryWeapon.img}}" />
                             <span>{{document.system.characterGuide.suggestedSecondaryWeapon.name}}</span>
                             <div class="controls">
-                                <i data-action="removeSuggestedItem" data-target="suggestedSecondaryWeapon" class="fa-solid fa-trash icon-button"></i>
+                                <a><i data-action="removeSuggestedItem" data-target="suggestedSecondaryWeapon" class="fa-solid fa-trash icon-button"></i></a>
```
Comment (joaquinpereyra98) [inline templates/sheets/items/class/settings.hbs]: Add action on anchor elements, not on the icon.

File: module/applications/sheets/api/application-mixin.mjs (hunk 2 above)
Comment (WBHarry) [reply module/applications/sheets/api/application-mixin.mjs]: I fiddled around a little with the idea of using `_onFirstRender` and `_onClose`. I felt it got difficult.

For my part, I'm good with leaving this as is and having it as something to redo at a later time if someone can make a good implementation.

File: module/applications/sheets/api/application-mixin.mjs [hunk 4]
```diff
@@ -496,7 +524,7 @@ export default function DHApplicationMixin(Base) {
          * Renders an embedded document.
          * @type {ApplicationClickAction}
          */
-        static #editDoc(_event, target) {
+        static async #editDoc(_event, target) {
```
Comment (joaquinpereyra98) [inline module/applications/sheets/api/application-mixin.mjs]: Made the asynchronous method but didn't await anything. Either remove the async, or await the render methods.

File: module/applications/sheets/api/application-mixin.mjs [hunk 5]
```diff
@@ -341,7 +356,20 @@ export default function DHApplicationMixin(Base) {
                 {
                     name: 'CONTROLS.CommonEdit',
                     icon: 'fa-solid fa-pen-to-square',
-                    callback: target => getDocFromElement(target).sheet.render({ force: true })
+                    callback: async target => {
```
Comment (joaquinpereyra98) [inline module/applications/sheets/api/application-mixin.mjs]: modify this callback

File: module/documents/tooltipManager.mjs [hunk 6]
```diff
@@ -13,7 +13,7 @@ export default class DhTooltipManager extends foundry.helpers.interaction.Toolti
             if (item) {
                 const type = actionId ? 'action' : item.type;
                 const description = await TextEditor.enrichHTML(item.system.description);
-                for (let feature of item.system.features) {
+                for (let feature of item.system?.features ?? []) {
                     feature.system.enrichedDescription = await TextEditor.enrichHTML(feature.system.description);
```
Comment (joaquinpereyra98) [inline module/documents/tooltipManager.mjs]: This should not take into account whether features is an array of Documents or an array of object type, items?
I've also seen that they localize this on the tmeplate? That doesn't make sense.

**Review by WBHarry — COMMENTED** [review]
In DamageRoll, `roll.roll` is a function that hasn't bene called if you use a damage action with `ShiftClick`. Errors out.
image

File: templates/sheets/items/class/settings.hbs [hunk 7]
```diff
@@ -42,7 +42,7 @@
                             <img class="image" src="{{document.system.characterGuide.suggestedPrimaryWeapon.img}}" />
                             <span>{{document.system.characterGuide.suggestedPrimaryWeapon.name}}</span>
                             <div class="controls">
-                                <i data-action="removeSuggestedItem" data-target="suggestedPrimaryWeapon" class="fa-solid fa-trash icon-button"></i>
+                                <a><i data-action="removeSuggestedItem" data-target="suggestedPrimaryWeapon" class="fa-solid fa-trash icon-button"></i></a>
```
Comment (joaquinpereyra98) [inline templates/sheets/items/class/settings.hbs]: Add action on anchor elements, not on the icon.

File: templates/sheets/items/class/settings.hbs [hunk 8]
```diff
@@ -72,7 +72,7 @@
                             <img class="image" src="{{document.system.characterGuide.suggestedArmor.img}}" />
                             <span>{{document.system.characterGuide.suggestedArmor.name}}</span>
                             <div class="controls">
-                                <i data-action="removeSuggestedItem" data-target="suggestedArmor" class="fa-solid fa-trash icon-button"></i>
+                                <a><i data-action="removeSuggestedItem" data-target="suggestedArmor" class="fa-solid fa-trash icon-button"></i></a>
```
Comment (joaquinpereyra98) [inline templates/sheets/items/class/settings.hbs]: Add action on anchor elements, not on the icon.

File: templates/sheets/items/class/settings.hbs [hunk 9]
```diff
@@ -86,13 +86,15 @@
...
-                            <img class="image" src="{{this.img}}" />
-                            <span>{{this.name}}</span>
-                            <div class="controls">
-                                <i data-action="removeItemFromCollection" data-target="invetory.take" data-uuid="{{this.uuid}}" class="fa-solid fa-trash icon-button"></i>
+                        {{#if this}}
+                            <div class="suggested-item item-line" data-action="editDoc" data-item-uuid="{{this.uuid}}">
+                                <img class="image" src="{{this.img}}" />
+                                <span>{{this.name}}</span>
+                                <div class="controls">
+                                    <a><i data-action="removeItemFromCollection" data-target="inventory.take" data-uuid="{{this.uuid}}" class="fa-solid fa-trash icon-button"></i></a>
```
Comment (joaquinpereyra98) [inline templates/sheets/items/class/settings.hbs]: Add action on anchor elements, not on the icon.

**Review by joaquinpereyra98 — CHANGES_REQUESTED** [review]

File: module/applications/sheets/api/base-item.mjs (hunk 1 above)
Comment (WBHarry) [reply module/applications/sheets/api/base-item.mjs:170]: It's added because we need to know the type in the filter function down below
```js
.filter(x => target.dataset.type !== x.type || x.item.uuid !== feature.uuid)
```

File: templates/sheets/items/class/settings.hbs (hunk 3 above)
Comment (WBHarry) [reply templates/sheets/items/class/settings.hbs]: Fixed :+1:

File: module/applications/sheets/api/application-mixin.mjs (hunk 4 above)
Comment (WBHarry) [reply module/applications/sheets/api/application-mixin.mjs]: Removed async. Originally I did other stuff in editDoc that needed it, but it wa removed again. :+1:

File: module/applications/sheets/api/application-mixin.mjs (hunk 5 above)
Comment (WBHarry) [reply module/applications/sheets/api/application-mixin.mjs]: Should be good now

File: templates/sheets/items/class/settings.hbs (hunk 7 above)
Comment (WBHarry) [reply templates/sheets/items/class/settings.hbs]: Fixed :+1:

File: templates/sheets/items/class/settings.hbs (hunk 8 above)
Comment (WBHarry) [reply templates/sheets/items/class/settings.hbs]: Fixed :+1:

File: templates/sheets/items/class/settings.hbs (hunk 9 above)
Comment (WBHarry) [reply templates/sheets/items/class/settings.hbs]: Fixed :+1:

File: module/documents/tooltipManager.mjs (hunk 6 above)
Comment (WBHarry) [reply module/documents/tooltipManager.mjs]: This I don't get.
Why does it matter if the data coming in is a document or an object type?

The features are not localized on the template, the description is rendered in the `tooltipTags.hbs` partial.
It's a very flexible render because it's used for Features and Actions from different sorts of data sources.
`<div class="tooltip-tag-description">{{{localize (ifThen feature.description feature.description (ifThen feature.system.enrichedDescription feature.system.enrichedDescription feature.system.description))}}}</div>`

File: module/applications/sheets/api/base-item.mjs (hunk 1 above)
Comment (WBHarry) [reply module/applications/sheets/api/base-item.mjs:170]: Could expand `getDocFromElement` to return both the doc and the matched HTMLElement, but eh..it's used in a ton of places, and it makes those implementations messier.
