### PR TITLE
[Fix] 1696 - Homebrew Fixes

### LINKED ISSUE #1694: [Feature] Saving new homebrew item feature should only require 1 click
Currently, if you add a new item feature under the homebrew menu, you need to click "save" twice: once on the feature window and once on the homebrew setting window. If either of these are missed (by clicking X to close the window instead), the new item feature is not saved and disappears, which makes it very easy to accidentally lose progress.

Image

### LINKED ISSUE #1695: [Bug] Adding an effect to a homebrew item feature deletes previous unsaved edits
1. Create a new item feature in the homebrew menu
2. Change the name of the feature, icon, description, etc.
3. Before saving changes, navigate to the effects tab and add a new effect
4. The feature name, icon, and description will be reset to their defaults

### LINKED ISSUE #1696: [Bug] Attempting to edit a new effect in the homebrew item features menu causes error message
Attempting to edit "New Effect" created when making a new effect in the homebrew item features menu has no effect and sends this error to the console:

Image

### PR DESCRIPTION
**Pull request by WBHarry**
Fixes #1694
Think it's a good idea. Changed it so that saving an ItemFeature makes it directly update the game setting so it's -actually- saved.

Fixes #1695
Since creating effects neccesitates updating the game setting, it will always lose any unsaved changes. So I changed it so that changes are directly saved to the game setting aswell. I don't really see the harm.

Fixes #1696 
SettingsActiveEffectConfig was out of date, making it error.
Moved the logic into a static method on ActiveEffectConfig so that both will always use the same logic to get their changeChoices for the autocomplete.

### CODE REVIEW

File: module/applications/sheets-configs/activeEffectConfig.mjs [hunk 1]
```diff
@@ -4,6 +4,38 @@ export default class DhActiveEffectConfig extends foundry.applications.sheets.Ac
...
+                { id: 'details', icon: 'fa-solid fa-book' },
+                { id: 'settings', icon: 'fa-solid fa-bars', label: 'DAGGERHEART.GENERAL.Tabs.settings' },
+                { id: 'changes', icon: 'fa-solid fa-gears' }
+            ],
+            initial: 'details',
+            labelPrefix: 'EFFECT.TABS'
+        }
+    };
+
+    static getChangeChoices() {
```
Comment (CarlosFdez) [inline module/applications/sheets-configs/activeEffectConfig.mjs:42]: I think it'd be handy to add a comment to this so that its meaning is clear. I can see us easily forgetting what this does.

File: module/applications/sheets-configs/setting-feature-config.mjs [hunk 2]
```diff
@@ -76,6 +76,9 @@ export default class SettingFeatureConfig extends HandlebarsApplicationMixin(App
     static async updateData(event, element, formData) {
         const data = foundry.utils.expandObject(formData.object);
         foundry.utils.mergeObject(this.move, data);
+        await this.settings.updateSource({
+            [`${this.movePath}`]: this.move
+        });
```
Comment (CarlosFdez) [inline module/applications/sheets-configs/setting-feature-config.mjs:80]: Out of curiousity (and not because there's anything wrong here) which of the issues is this particular line trying to solve?

**Comment by CarlosFdez** [comment]
All of those issues make sense to me.

File: module/applications/sheets-configs/activeEffectConfig.mjs (hunk 1 above)
Comment (WBHarry) [reply module/applications/sheets-configs/activeEffectConfig.mjs:42]: Added a comment:
```
/**
 * Get ChangeChoices for the changes autocomplete. Static for use in this class aswell as in settings-active-effect-config.mjs
 * @returns {ChangeChoice { value: string, label: string, hint: string, group: string }[]}
 */
```

File: module/applications/sheets-configs/setting-feature-config.mjs (hunk 2 above)
Comment (WBHarry) [reply module/applications/sheets-configs/setting-feature-config.mjs:80]: Yeah, this was a bit confusing.

I went through and replaced all updates to run through a single method now:
```
async updateMove(update) {
    await this.settings.updateSource(update);
    this.move = foundry.utils.getProperty(this.settings, this.movePath);
}
```
