### PR TITLE
286 - Adversary Experience Value Bug

### LINKED ISSUE #286: [BUG] - Adversary Experience display Nan when used in rolls
**Describe the bug**
Adversary Experience display as Nan when used in rolls, breaking the dice roll.

**To Reproduce**
1. Open an Adversary.
2. Make any roll.
3. Add an experience to the roll.
4. See error.

**Expected behavior**
Experiences are properly applied to the rolls.

**Screenshots**

**Setup Information:**
On Phone will fill out when home.
 - OS: Windows 11
 - Foundry Version [e.g. v13 b342]
- System Version [e.g. main-3593f44]

### PR DESCRIPTION
**Pull request by WBHarry**
## Description
Changed experience schema field name from 'modifier' to 'total' to match useage in Character and Companion

- Closes #286 

## Type of Change
- [x] Bug fix

## How Has This Been Tested?
- [x] Manual testing
- [ ] Other:

### CODE REVIEW

File: module/applications/sheets/actors/adversary.mjs [hunk 1]
```diff
@@ -92,9 +92,7 @@ export default class AdversarySheet extends DHBaseActorSheet {
             const cls = getDocumentClass('ChatMessage');
             const systemData = {
                 name: game.i18n.localize('DAGGERHEART.GENERAL.Experience.single'),
-                description: `${experience.name} ${
-                    experience.modifier < 0 ? experience.modifier : `+${experience.modifier}`
-                }`
+                description: `${experience.name} ${experience.total < 0 ? experience.total : `+${experience.total}`}`
```
Comment (joaquinpereyra98) [inline module/applications/sheets/actors/adversary.mjs]: if you want to get the signed string of a number you can do
````js
myNumber.signedString()
````
https://foundryvtt.com/api/v13/functions/primitives.Number.signedString.html

Comment (WBHarry) [reply module/applications/sheets/actors/adversary.mjs]: Awesome. Good to know 👍
